version: 2

models:
  - name: product_summary
    description: This model aggregates product data by country and product, over the past year.
    columns:
      - name: country             
  
  - name: count_facilties
    description: This model gets the total sum of facilities per city.
    
  - name: stg_sales
    description: This staging model renames columns from the raw data.
  
      
            